# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclangtarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "i9KrHoWt9XiBuB2btErBJck38zIXb2J2LWV5tj3Ddy36Vroh5gRTITWbLJ5S7titCXtyMe5P5baGcBVbwdzilZ2cN0WTnwmNx6UbpLXSLjmqup8yIdhgilnu3FGIvNEH52l/+16RwaKVRiJcJrNpNrzx5+Q4KuDZ+lpMJZf6uMnlEPVeR+G49XMvaV2c6TLFp4aWcLRO4teV75QFVH8WHfshxOHVnFm1RcKWWTfy+EvFAJ8NunpeqAlCTJJp/YiZDuKoWyl+X6uvmDn4GJDHaQP8ILHIyHI9EBJjWBeamUQDhl13y0JdjSXV38XQiW8HLNbkP4W7T0GmIIxYiLdKQhszW8k6HqjDcmZ3AnlSHawGVbIk/RpIGOF1WaJr1h9YEcsaBIuiJaRii3LaI0zo6vcpz3sBIXG5GTYVu5yvVRt81UkJYUmt0L97K8bmHVsJ6UJHE4NjugZSJ/NTVWURgrFzKK6s/JnptKpcmL3UxTOrE8Fk178/qZ2ijvk9PdwJCxBtyRe9eCUjoWpxS5dwsSH76NX6vKkMLK+43clVJZK6ii8Vm5bauk2tZcYnTsdnQtIuU7vnvNFeR5TpLlHkiqU12hhI5ulPsCr7nAcpCQ6K5IuFd9xQhfRKvMWZRH2rq3RwH6QA4Zm02QkpYDg//ukNL4FlW5K7XKEve0rp748="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml