appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: i9KrHoWt9XiBuB2btErBJck38zIXb2J2LWV5tj3Ddy36Vroh5gRTITWbLJ5S7titCXtyMe5P5baGcBVbwdzilZ2cN0WTnwmNx6UbpLXSLjmqup8yIdhgilnu3FGIvNEH52l/+16RwaKVRiJcJrNpNrzx5+Q4KuDZ+lpMJZf6uMnlEPVeR+G49XMvaV2c6TLFp4aWcLRO4teV75QFVH8WHfshxOHVnFm1RcKWWTfy+EvFAJ8NunpeqAlCTJJp/YiZDuKoWyl+X6uvmDn4GJDHaQP8ILHIyHI9EBJjWBeamUQDhl13y0JdjSXV38XQiW8HLNbkP4W7T0GmIIxYiLdKQhszW8k6HqjDcmZ3AnlSHawGVbIk/RpIGOF1WaJr1h9YEcsaBIuiJaRii3LaI0zo6vcpz3sBIXG5GTYVu5yvVRt81UkJYUmt0L97K8bmHVsJ6UJHE4NjugZSJ/NTVWURgrFzKK6s/JnptKpcmL3UxTOrE8Fk178/qZ2ijvk9PdwJCxBtyRe9eCUjoWpxS5dwsSH76NX6vKkMLK+43clVJZK6ii8Vm5bauk2tZcYnTsdnQtIuU7vnvNFeR5TpLlHkiqU12hhI5ulPsCr7nAcpCQ6K5IuFd9xQhfRKvMWZRH2rq3RwH6QA4Zm02QkpYDg//ukNL4FlW5K7XKEve0rp748=}
